from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from ..database import get_db
from ..models import Device, Alert, Process, FileEvent, Investigation
import datetime

router = APIRouter(prefix="/api")

@router.get("/device/{device_id}/report")
def generate_device_report(device_id: str, db: Session = Depends(get_db)):
    """
    Assembles a comprehensive, downloadable Markdown incident investigation report
    for the selected device.
    """
    device = db.query(Device).filter(Device.id == device_id).first()
    if not device:
        raise HTTPException(status_code=404, detail="Device not found")

    alerts = db.query(Alert).filter(Alert.device_id == device_id).all()
    processes = db.query(Process).filter(Process.device_id == device_id).all()
    file_events = db.query(FileEvent).filter(FileEvent.device_id == device_id).limit(10).all()
    latest_investigation = db.query(Investigation).filter(Investigation.device_id == device_id).order_by(Investigation.created_at.desc()).first()

    # Calculate statistics
    total_alerts = len(alerts)
    unresolved_alerts = sum(1 for a in alerts if a.status == "UNRESOLVED")
    critical_alerts = sum(1 for a in alerts if a.severity.upper() == "CRITICAL")
    high_alerts = sum(1 for a in alerts if a.severity.upper() == "HIGH")
    medium_alerts = sum(1 for a in alerts if a.severity.upper() == "MEDIUM")
    low_alerts = sum(1 for a in alerts if a.severity.upper() == "LOW")

    report_md = f"""# PESZARA XDR - SECURITY ASSESSMENT REPORT
**Generated on**: {datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")} UTC
**Scope**: Device-Specific Security Telemetry Log

---

## 1. DEVICE OVERVIEW
| Asset Attribute | Metric Detail |
| :--- | :--- |
| **Hostname** | {device.hostname} |
| **Device ID** | {device.id} |
| **Operating System** | {device.os_name} ({device.os_version}) |
| **Local IP Address** | {device.ip_address} |
| **Active Host User** | {device.logged_in_user or 'N/A'} |
| **Overall Risk Score** | **{device.risk_score}/100** |
| **Telemetry Last Seen** | {device.last_seen.strftime("%Y-%m-%d %H:%M:%S")} UTC |

---

## 2. INCIDENT SUMMARY & METRICS
* **Total Logged Alerts**: {total_alerts}
* **Active (Unresolved) Alerts**: {unresolved_alerts}
* **Threat Distribution**:
  * Critical: `{critical_alerts}`
  * High: `{high_alerts}`
  * Medium: `{medium_alerts}`
  * Low: `{low_alerts}`

### Active Alert Registry
"""
    if alerts:
        report_md += "| Alert Title | Severity | MITRE Tactic | Technique | Status |\n| :--- | :--- | :--- | :--- | :--- |\n"
        for a in alerts:
            report_md += f"| {a.title} | {a.severity} | {a.mitre_tactic or 'N/A'} | {a.mitre_technique or 'N/A'} | {a.status} |\n"
    else:
        report_md += "*No security alerts have been flagged on this endpoint.*\n"

    report_md += "\n---\n\n## 3. LATEST AI INVESTIGATION RESULTS (COPILOT)\n"
    if latest_investigation:
        report_md += f"### Incident Narrative\n{latest_investigation.summary}\n\n"
        report_md += f"### Chronological Attack Chain Details\n{latest_investigation.analysis}\n\n"
        report_md += f"### Actionable Incident Response Steps\n{latest_investigation.remediation}\n"
    else:
        report_md += "*No AI Investigation has been requested for this host. Trigger Copilot Analysis from the main dashboard first.*\n"

    report_md += "\n---\n\n## 4. PROCESS INVENTORY SUMMARY\n"
    report_md += f"Currently running active process count: `{len(processes)}`\n"
    if processes:
        report_md += "\n| PID | Parent PID | Executable | Active User | SHA-256 Hash |\n| :--- | :--- | :--- | :--- | :--- |\n"
        for p in processes[:15]: # Show top 15 for brevity
            sha_display = (p.sha256[:10] + "...") if p.sha256 else "N/A"
            report_md += f"| {p.pid} | {p.ppid or 'N/A'} | {p.name} | {p.username or 'N/A'} | {sha_display} |\n"
        if len(processes) > 15:
            report_md += f"| ... | ... | (*and {len(processes) - 15} more processes*) | ... | ... |\n"

    report_md += "\n---\n\n## 5. FILE MODIFICATION HISTORY (LATEST EVENTS)\n"
    if file_events:
        report_md += "| Action | Filepath | Log Time |\n| :--- | :--- | :--- |\n"
        for fe in file_events:
            report_md += f"| {fe.action} | {fe.filepath} | {fe.timestamp.strftime('%H:%M:%S')} |\n"
    else:
        report_md += "*No file modification telemetry captured on this device.*"

    report_md += """

---
*Report generated by PESZARA XDR Endpoint Security Platform. Proprietary asset data logs.*
"""

    return {
        "device_id": device_id,
        "hostname": device.hostname,
        "report_markdown": report_md
    }
